### ISSUE TITLE
Support for fragments

### ISSUE THREAD

**Issue by terlar** [soylent/jschema#7]
Is this something that we want to support? I have created a small wrapper and could compile a pull-request if you feel it belongs to this project.

I just do this basically:
```ruby
schema_a = JSchema.build(schema_data);
schema_b = JSchema.build({ '$ref' => fragment }, schema_a)
```

I found it quite elegant in the way that it didn't affect the code that much.

I would suggest having something like `schema.fragment(uri)` which would return a new `JSchema::Schema`.

**Comment by soylent** [comment]
@terlar sorry for the late reply. I like the idea, feel free to send a PR.
